java_library(
    name = "transaction",
    srcs = [
        "RocksDatabase.java",
        "RocksTransaction.java",
    ],
    deps = [
        "//dependencies/maven/artifacts/org/rocksdb:rocksdbjni"
#        "//dependencies/tools:speedb-rocksdb-jni"
    ],
    visibility = ["//visibility:public"],
)
